### ISSUE TITLE
Download Unreal Engine

### ISSUE THREAD

**Issue by CodeRhymesLife** [CodeRhymesLife/Mikevator#1]
We'll use Unreal Engine to lean about and build our augmented reality world. First you'll need to download unreal engine by doing the following:

1) Get Unreal: https://www.unrealengine.com/dashboard
2) Install Unreal
3) Open Unreal
4) Download unreal engine:
    4a) In the upper left hand corner you'll see a yellow box telling you to download the engine
    4b) Click the box and download unreal engine 4.10.0

If you have any trouble with this leave a comment in this bug to let me know what the issue is.

When you've finished this bug close it using the button below (do this will all bugs you've finished)

**Comment by ibeamarioh** [comment]
The process is straight but I got an error. 
[U4 Error - Error Code 23.pptx](https://github.com/rcjames1004/Mikevator/files/71444/U4.Error.-.Error.Code.23.pptx)

**Comment by CodeRhymesLife** [comment]
@ibeamarioh, did you try updating windows?

Thanks for the screenshot.

**Comment by ibeamarioh** [comment]
nevermind, problem solved.

**Comment by CodeRhymesLife** [comment]
Sweet.
